runtime: python39
instance_class: F4_1G
default_expiration: "10m"
env_variables:
  CLOUD_STORAGE_BUCKET: data_truchiwoman
  SERVER_TYPE: GCP
  VERBOSE: False

handlers:
- url: /static
  static_dir: static